### ISSUE TITLE
Modal docs should pass object to modal.set function instead of deprecated name/value pair

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-site#5] opened 2016-08-23 15:17 UTC
The Modal documentation page use the depracted way for setting properties on a Modal instance.

Instead of : 

`modal.set('minimized', true)
`

We have to do this : 

```
modal.set({
    minimized: true
  })
```

Second potential issue, with the new 0.6.0 release, passing 

```
.set({
 'selfDestroy': false
 })
```

to the modal instance disables all click events on the document.

**Comment by mlenormand** [comment] 2016-08-23 15:25
Well, I think I found where is the problem : when closing the Modal without destroying it, we should disable the "backdrop" (i.e enable again the clicks in the body area)

**Comment by rstoenescu** [comment] 2016-08-23 15:27
Aaah, you are right. Will make a patch shortly and release v0.6.1. Thanks!

**Comment by rstoenescu** [comment] 2016-08-23 15:28
Meanwhile updated doc.

**Comment by rstoenescu** [comment] 2016-08-23 15:41
Hmm, cannot reproduce. Also checked the code and everything seems to be ok.

**Comment by rstoenescu** [comment] 2016-08-23 15:44
So what I'm doing is creating a button which triggers `toggleModal()` from below.

``` js
export default {
  compiled () {
    this.modal = Modal.create({
      template: 'Modal will close shortly'
    }).set({
      selfDestroy: false,
      minimized: true
    })
  },
  beforeDestroy () {
    this.modal.destroy()
  },
  methods: {
    toggleModal () {
      this.modal.show()
      setTimeout(() => {
        this.modal.close()
      }, 2000)
    }
  }
}
```

**Comment by rstoenescu** [comment] 2016-08-23 15:52
You could have a Javascript error thrown which breaks the JS flow so Quasar can't do its job properly closing the Modal... Otherwise I don't see how this can happen. Keep me posted please.

**Comment by mlenormand** [comment] 2016-08-23 15:55
It's OK, no bug, I kept my old code that was creating a new Modal on each click. You can close it.

**Closed** 2016-08-23 15:56 UTC
